"""
Django settings for comer_web project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import configparser

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
current_dir = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(os.path.dirname(current_dir))

from comer_web.settings import passwords

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = passwords.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
try:
    from comer_web.settings.debug import DEBUG
except ImportError:
    DEBUG = False

BASE_URL = 'https://bioinformatics.lt/comer'
ALLOWED_HOSTS = ['.ibt.lt', '.bioinformatics.lt', '.bioinfo.lt', 'localhost']

CSRF_TRUSTED_ORIGINS = ['https://bioinformatics.lt',]

EMAIL_HOST = 'mailrelay.vu.lt'
DEFAULT_FROM_EMAIL = 'comer@bti.vu.lt'

# Add Google Analytics tag into file google_analytics.py if you want to use
# this service.
try:
    from comer_web.settings.google_analytics import GOOGLE_ANALYTICS_CODE
except ImportError:
    GOOGLE_ANALYTICS_CODE = ''

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cookielaw',
    'apps.databases',
    'apps.core',
    'apps.search',
    'apps.model_structure',
    'apps.msa',
    'apps.website',
    'apps.structure_search',
    'apps.superposition',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'comer_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cookielaw.context_processors.cookielaw',
                'comer_web.context_processors.google_analytics',
                'comer_web.context_processors.program_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'comer_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'comer_web_server',
        'USER': passwords.MYSQL_USER,
        'PASSWORD': passwords.MYSQL_PASSWORD,
        'HOST': '127.0.0.1',
        'OPTIONS': {
            'charset': 'utf8',
        }
    }
}

JOBS_DIRECTORY = '/opt/comer_web/jobs'

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = '/opt/comer_web/static'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# COMER server settings

DATA_UPLOAD_MAX_NUMBER_FIELDS = 1010
