search_settings = {
    # COMER settings
    'EVAL': 10.0,
    'NOHITS': 700,
    'NOALNS': 700,
    'SHOW': 1,
    'DSCLEN': 1024,
    'DSCWIDTH': 80,
    'ALNWIDTH': 60,
    'X_UNINF': 1,
    'IDENTITY': 90,
    'SHOWCMD': 0,
    'PCFWEIGHT': 1.5,
    'MINALNFRN': 5,
    'MINALNPOS': 10,
    'SUBMAT': 'Gonnet',
    'SCOADJ': 'hdpsco',
    'SUPCLT': 5,
    'ADJWGT': 0.33,
    'cADJWGT': 0.33,
    'CVSWGT': 0.15,
    'SSSWGT': 0.12,
    'SSEMODEL': 2,
    'HCFILTER': 0,
    'HCWINDOW': 12,
    'HCLOWENT': 3.3,
    'HCHIGHENT': 3.4,
    'INVLCFILTER': 0,
    'LCFILTEREACH': 1,
    'LCWINDOW': 8,
    'LCLOWENT': 1.6,
    'LCHIGHENT': 1.6,
    'DISTANCE': 12.96,
    'MAPALN': 1,
    'MINPP': 0.28,
    # COTHER settings
    #'DSTSEGM': 6,
    #'DSTNPOS': 12,
    #'DSTSEP6': 12,
    #'DSTGAPL': 24,
    #'DSTFREE': 3,
    # MSA for profile generation settings
    'hhsuite_in_use': True,
    'hhsuite_opt_niterations': 2,
    'hhsuite_opt_evalue': 0.001,
    'hmmer_in_use': False,
    'hmmer_opt_niterations': 2,
    'hmmer_opt_evalue': 0.001,
}
number_of_results = 700
