---
- name: Install Python3 on host machines, if necessary
  hosts: all
  become: true
  gather_facts: false
  tasks:
      - name: Check for Python3
        raw: which python3
        changed_when: false
        failed_when: false
        register: check_python
      - name: Install Python3
        raw: dnf -y install python3
        when: check_python.rc != 0
- name: Install necessary software and configure environment
  hosts: all
  become: true
  tasks:
      - name: Remove conflicting packages, if they are installed
        dnf:
            name: '{{ item }}'
            state: absent
        loop:
            - mysql
            - mysql-server
        tags:
            - install-dnf
      - name: Install CentOS packages
        dnf:
            name: '{{ item }}'
            state: present
        loop:
            - epel-release
            - httpd
            - git
            - mc
            - vim-enhanced
            - python3-devel
            - python3-virtualenv
            - python3-mod_wsgi
            - mariadb
            - mariadb-server
            - mariadb-devel
            - python3-mysql
            - gcc
        tags:
            - install-dnf
      - name: Configure firewall to allow httpd connections
        firewalld:
            service: http
            zone: public
            permanent: true
            immediate: yes
            state: enabled
        ignore_errors: yes
        tags:
            - firewall
      - name: Configure DB server firewall to allow MySQL connections
        firewalld:
            service: mysql
            zone: public
            permanent: true
            immediate: yes
            state: enabled
        tags:
            - firewall
      - name: Create user for COMER server tasks
        user:
            name: comerws
            uid: 2021
      - name: Create directories for COMER web server
        file:
            path: '/opt/comer_web/{{ item }}'
            state: directory
            mode: 02775
            owner: comerws
            group: comerws
        loop:
            - jobs
            - logs
            - static
            - dependencies
      - name: Set permissions for user apache
        acl:
            path: /opt/comer_web/
            entry: default:user:apache:rwx
            state: present
            recursive: yes
      - name: Start necessary services
        service:
            name: '{{ item }}'
            state: started
            enabled: true
        loop:
            - mariadb
- name: Install JavaScript dependencies
  hosts: all
  become: true
  tasks:
    - name: Download NGL Viewer
      git:
          repo: 'https://github.com/nglviewer/ngl'
          dest: '/opt/comer_web/dependencies/ngl'
    - name: Copy NGL Viewer to static files directory
      copy:
          remote_src: yes
          src: '/opt/comer_web/dependencies/ngl/dist/ngl.js'
          dest: '/opt/comer_web/static'
    - name: Get Bootstrap CSS
      get_url:
          url: 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css'
          dest: '/opt/comer_web/static'
    - name: Get Bootstrap JavaScript
      get_url:
          url: 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js'
          dest: '/opt/comer_web/static'
- name: Download COMER web software and do initial setup
  hosts: all
  become: true
  tasks:
      - name: Get COMER web server software
        git:
            repo: 'https://github.com/chemikeris/comer_web.git'
            dest: /opt/comer_web/src
        tags:
            - github
...
